// Índice de exportación de todas las entidades
export * from './colegio.entity';
export * from './rol.entity';
export * from './usuario.entity';
export * from './periodo.entity';
export * from './materia.entity';
export * from './desempeno.entity';
export * from './sede.entity';
export * from './curso.entity';
export * from './estudiante.entity';
export * from './coordinador-sede.entity';
export * from './profesor-asignacion.entity';
export * from './nota.entity';
export * from './recuperacion.entity';
export * from './cierre-periodo.entity';
export * from './auditoria.entity';
export * from './sync-device.entity';
export * from './sync-queue.entity';
export * from './asistencia.entity';
